server:
  port: 8085
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/melodicdeath/spring-cloud-learn.git
          username: zt.freedom@gmail.com
          password: mymelody891004
          search-paths: microservice-config-server
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.boot: DEBUG
info:
  test: 1