server:
  port: 8080
spring:
  application:
    name: microservice-consumer-movie

eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://peer1:8081/eureka/,http://peer2:8082/eureka/